<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Menu;
use Illuminate\Support\Facades\Schema;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            // Dashboard
            [
                'id' => 'b5a9bdd7-5939-4008-91b9-ce77c3483e03',
                'parent_id' => null,
                'name' => 'Dashboard',
                'code' => 'dashboard',
                'text_sidebar' => 'Dashboard',
                'icon' => 'ti ti-smart-home',
                'has_page' => false,
                'url_path' => 'dashboard',
                'route_name' => 'dashboard',
                'slug' => 'dashboard',
                'level_sidebar' => 1,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Human Resources (Parent)
            [
                'id' => '9d47eecd-6779-4b6a-9730-3f05b8db104a',
                'parent_id' => null,
                'name' => 'Human Resources',
                'code' => 'human_resources',
                'text_sidebar' => 'Human Resources',
                'icon' => 'ti ti-users',
                'has_page' => true,
                'url_path' => 'human-resources',
                'route_name' => null,
                'slug' => 'human-resources',
                'level_sidebar' => 1,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Human Resources > Master (Sub-group)
            [
                'id' => '9d47eecd-0001-4b6a-9730-3f05b8db104a',
                'parent_id' => '9d47eecd-6779-4b6a-9730-3f05b8db104a',
                'name' => 'Master',
                'code' => 'hr_master',
                'text_sidebar' => 'Master',
                'icon' => 'ti ti-database',
                'has_page' => true,
                'url_path' => 'human-resources/master',
                'route_name' => null,
                'slug' => 'hr-master',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Human Resources > Master > Division
            [
                'id' => 'b8f4e5d2-3a1c-4f6b-9e7d-2c5a8b1f4e6d',
                'parent_id' => '9d47eecd-0001-4b6a-9730-3f05b8db104a',
                'name' => 'Division',
                'code' => 'division',
                'text_sidebar' => 'Division',
                'icon' => 'ti ti-users',
                'has_page' => false,
                'url_path' => 'human-resources/division',
                'route_name' => 'division.index.view',
                'slug' => 'division',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Human Resources > Master > Position
            [
                'id' => '8d736dbf-ba2e-470c-859e-d8967c579b0c',
                'parent_id' => '9d47eecd-0001-4b6a-9730-3f05b8db104a',
                'name' => 'Position',
                'code' => 'position',
                'text_sidebar' => 'Position',
                'icon' => 'ti ti-briefcase',
                'has_page' => false,
                'url_path' => 'human-resources/position',
                'route_name' => 'position.index.view',
                'slug' => 'position',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Human Resources > Employee
            [
                'id' => 'a29ab2a8-c692-4029-8bd8-cf77f0901e8c',
                'parent_id' => '9d47eecd-6779-4b6a-9730-3f05b8db104a',
                'name' => 'Employee',
                'code' => 'employee',
                'text_sidebar' => 'Employee',
                'icon' => 'ti ti-users',
                'has_page' => false,
                'url_path' => 'human-resources/employee',
                'route_name' => 'users.index.view',
                'slug' => 'employee',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Customer (Parent) - top level, below Human Resources
            [
                'id' => 'b29ab2a8-0001-4029-8bd8-cf77f0901e8c',
                'parent_id' => null,
                'name' => 'Customer',
                'code' => 'customer',
                'text_sidebar' => 'Customer',
                'icon' => 'ti ti-users',
                'has_page' => true,
                'url_path' => 'customer',
                'route_name' => null,
                'slug' => 'customer',
                'level_sidebar' => 1,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Customer > Group
            [
                'id' => 'b29ab2a8-0002-4029-8bd8-cf77f0901e8c',
                'parent_id' => 'b29ab2a8-0001-4029-8bd8-cf77f0901e8c',
                'name' => 'Group',
                'code' => 'customer_group',
                'text_sidebar' => 'Group',
                'icon' => 'ti ti-users',
                'has_page' => false,
                'url_path' => 'customer/group',
                'route_name' => 'customer.group.index',
                'slug' => 'customer-group',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Customer > List
            [
                'id' => 'b29ab2a8-0003-4029-8bd8-cf77f0901e8c',
                'parent_id' => 'b29ab2a8-0001-4029-8bd8-cf77f0901e8c',
                'name' => 'List',
                'code' => 'customer_list',
                'text_sidebar' => 'List',
                'icon' => 'ti ti-list',
                'has_page' => false,
                'url_path' => 'customer/list',
                'route_name' => 'customer.list.index',
                'slug' => 'customer-list',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product (Parent) - Unified Product Master
            [
                'id' => 'a7b8c9d0-e1f2-4a5b-9c8d-7e6f5a4b3c2d',
                'parent_id' => null,
                'name' => 'Product',
                'code' => 'product',
                'text_sidebar' => 'Product',
                'icon' => 'ti ti-package',
                'has_page' => true,
                'url_path' => 'product',
                'route_name' => null,
                'slug' => 'product',
                'level_sidebar' => 1,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // === Product > Master (Sub-group) ===
            [
                'id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'parent_id' => 'a7b8c9d0-e1f2-4a5b-9c8d-7e6f5a4b3c2d',
                'name' => 'Master',
                'code' => 'product_master',
                'text_sidebar' => 'Master',
                'icon' => 'ti ti-database',
                'has_page' => true,
                'url_path' => 'product/master',
                'route_name' => null,
                'slug' => 'product-master',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Product Type
            [
                'id' => 'b8c9d0e1-0001-4b5c-0d9e-8f7a6b5c4d3e',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Product Type',
                'code' => 'product_type',
                'text_sidebar' => 'Product Type',
                'icon' => 'ti ti-category',
                'has_page' => false,
                'url_path' => 'product/nature',
                'route_name' => 'product.nature.index.view',
                'slug' => 'product-type',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Unit
            [
                'id' => 'c9d0e1f2-a3b4-4c5d-1e0f-9a8b7c6d5e4f',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Unit',
                'code' => 'product_unit',
                'text_sidebar' => 'Unit',
                'icon' => 'ti ti-ruler',
                'has_page' => false,
                'url_path' => 'product/satuan',
                'route_name' => 'product.unit.index.view',
                'slug' => 'product-unit',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Category
            [
                'id' => 'c9d0e1f2-a3b4-4c5d-1e0f-9a8b7c6d5e50',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Category',
                'code' => 'product_category',
                'text_sidebar' => 'Category',
                'icon' => 'ti ti-folders',
                'has_page' => false,
                'url_path' => 'product/category',
                'route_name' => 'product.category.index.view',
                'slug' => 'product-category',
                'level_sidebar' => 3,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Items (moved from Master > Product)
            [
                'id' => 'd0e1f2a3-b4c5-4d6e-2f1a-0b9c8d7e6f5a',
                'parent_id' => 'a7b8c9d0-e1f2-4a5b-9c8d-7e6f5a4b3c2d',
                'name' => 'Items',
                'code' => 'product_item',
                'text_sidebar' => 'Items',
                'icon' => 'ti ti-box',
                'has_page' => false,
                'url_path' => 'product/items',
                'route_name' => 'product.index.view',
                'slug' => 'product-item',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Price Lists
            [
                'id' => 'e1f2a3b4-c5d6-4e7f-3a2b-1c0d9e8f7a6c',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Price Lists',
                'code' => 'product_price_lists',
                'text_sidebar' => 'Price Lists',
                'icon' => 'ti ti-tag',
                'has_page' => false,
                'url_path' => 'product/price-list',
                'route_name' => 'product.price-list.index.view',
                'slug' => 'product-price-lists',
                'level_sidebar' => 3,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Attribute
            [
                'id' => 'e1f2a3b4-c5d6-4e7f-3a2b-1c0d9e8f7a8b',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Attribute',
                'code' => 'attribute',
                'text_sidebar' => 'Attribute',
                'icon' => 'ti ti-list-check',
                'has_page' => false,
                'url_path' => 'product/attribute',
                'route_name' => 'product.attribute.index.view',
                'slug' => 'attribute',
                'level_sidebar' => 3,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // === Product > Pricing (Sub-group) ===
            [
                'id' => 'a3b4c5d6-e7f8-4a9b-5c4d-3e2f1a0b9c8d',
                'parent_id' => 'a7b8c9d0-e1f2-4a5b-9c8d-7e6f5a4b3c2d',
                'name' => 'Pricing',
                'code' => 'product_pricing',
                'text_sidebar' => 'Pricing',
                'icon' => 'ti ti-currency-dollar',
                'has_page' => true,
                'url_path' => 'product/price',
                'route_name' => null,
                'slug' => 'product-pricing',
                'level_sidebar' => 2,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Pricing > Product Price
            [
                'id' => 'a3b4c5d6-0001-4a9b-5c4d-3e2f1a0b9c8d',
                'parent_id' => 'a3b4c5d6-e7f8-4a9b-5c4d-3e2f1a0b9c8d',
                'name' => 'Product Price',
                'code' => 'product_price',
                'text_sidebar' => 'Product Price',
                'icon' => 'ti ti-receipt',
                'has_page' => false,
                'url_path' => 'product/price',
                'route_name' => 'product.price.index.view',
                'slug' => 'product-price',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // === Product > Inventory (Sub-group) ===
            [
                'id' => 'f2a3b4c5-d6e7-4f8a-4b3c-2d1e0f9a8b7c',
                'parent_id' => 'a7b8c9d0-e1f2-4a5b-9c8d-7e6f5a4b3c2d',
                'name' => 'Inventory',
                'code' => 'product_inventory',
                'text_sidebar' => 'Inventory',
                'icon' => 'ti ti-box',
                'has_page' => true,
                'url_path' => 'product/stock',
                'route_name' => null,
                'slug' => 'product-inventory',
                'level_sidebar' => 2,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Inventory > Stock Opname
            [
                'id' => 'f2a3b4c5-0002-4f8a-4b3c-2d1e0f9a8b7c',
                'parent_id' => 'f2a3b4c5-d6e7-4f8a-4b3c-2d1e0f9a8b7c',
                'name' => 'Stock Opname',
                'code' => 'stock_opname',
                'text_sidebar' => 'Stock Opname',
                'icon' => 'ti ti-clipboard-check',
                'has_page' => true,
                'url_path' => 'product/stock-opname',
                'route_name' => 'product.stock-opname.index',
                'slug' => 'stock-opname',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Inventory > Stock
            [
                'id' => 'f2a3b4c5-0001-4f8a-4b3c-2d1e0f9a8b7c',
                'parent_id' => 'f2a3b4c5-d6e7-4f8a-4b3c-2d1e0f9a8b7c',
                'name' => 'Stock',
                'code' => 'product_stock',
                'text_sidebar' => 'Stock',
                'icon' => 'ti ti-box',
                'has_page' => false,
                'url_path' => 'product/stock',
                'route_name' => 'product.stock.index.view',
                'slug' => 'product-stock',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Inventory > Stock Adjustment
            [
                'id' => 'd3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e',
                'parent_id' => 'f2a3b4c5-d6e7-4f8a-4b3c-2d1e0f9a8b7c',
                'name' => 'Stock Adjustment',
                'code' => 'stock_adjustment',
                'text_sidebar' => 'Stock Adjustment',
                'icon' => 'ti ti-adjustments-alt',
                'has_page' => false,
                'url_path' => 'product/stock-adjustment',
                'route_name' => 'product.stock-adjustment.index',
                'slug' => 'stock-adjustment',
                'level_sidebar' => 3,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // === Product > Purchasing (Sub-group) ===
            [
                'id' => 'a1b2c3d4-0005-4f8a-4b3c-2d1e0f9a8b7c',
                'parent_id' => 'a7b8c9d0-e1f2-4a5b-9c8d-7e6f5a4b3c2d',
                'name' => 'Purchasing',
                'code' => 'purchasing',
                'text_sidebar' => 'Purchasing',
                'icon' => 'ti ti-shopping-cart',
                'has_page' => true,
                'url_path' => 'master-data/supplier',
                'route_name' => null,
                'slug' => 'purchasing',
                'level_sidebar' => 2,
                'order_number' => 7,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Purchasing > Supplier
            [
                'id' => 'b2c3d4e5-0006-4f8a-4b3c-2d1e0f9a8b7c',
                'parent_id' => 'a1b2c3d4-0005-4f8a-4b3c-2d1e0f9a8b7c',
                'name' => 'Supplier',
                'code' => 'supplier',
                'text_sidebar' => 'Supplier',
                'icon' => 'ti ti-truck',
                'has_page' => false,
                'url_path' => 'master-data/supplier',
                'route_name' => 'product.supplier.index.view',
                'slug' => 'supplier',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Purchasing > Purchase Order
            [
                'id' => 'b2c3d4e5-0007-4f8a-4b3c-2d1e0f9a8b7c',
                'parent_id' => 'a1b2c3d4-0005-4f8a-4b3c-2d1e0f9a8b7c',
                'name' => 'Purchase Order',
                'code' => 'purchase_order',
                'text_sidebar' => 'Purchase Order',
                'icon' => 'ti ti-file-invoice',
                'has_page' => false,
                'url_path' => 'product/purchase-order',
                'route_name' => 'product.purchase-order.index.view',
                'slug' => 'purchase-order',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Tag (moved from Product > Tag)
            [
                'id' => 'e1f2a3b4-c5d6-4e7f-3a2b-1c0d9e8f7a9b',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Tag',
                'code' => 'product_tag',
                'text_sidebar' => 'Tag',
                'icon' => 'ti ti-tag',
                'has_page' => false,
                'url_path' => 'product/tag',
                'route_name' => 'product.tag.index.view',
                'slug' => 'product-tag',
                'level_sidebar' => 3,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Product > Master > Collection (moved from Product > Collection)
            [
                'id' => 'e1f2a3b4-c5d6-4e7f-3a2b-1c0d9e8f7aab',
                'parent_id' => 'b8c9d0e1-f2a3-4b5c-0d9e-8f7a6b5c4d3e',
                'name' => 'Collection',
                'code' => 'product_collection',
                'text_sidebar' => 'Collection',
                'icon' => 'ti ti-folders',
                'has_page' => false,
                'url_path' => 'product/collection',
                'route_name' => 'product.collection.index.view',
                'slug' => 'product-collection',
                'level_sidebar' => 3,
                'order_number' => 7,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Point of Sales (Parent)
            [
                'id' => 'a0b1c2d3-e4f5-4a5b-8c9d-0e1f2a3b4c5e',
                'parent_id' => null,
                'name' => 'Point of Sales',
                'code' => 'point_of_sales',
                'text_sidebar' => 'Point of Sales',
                'icon' => 'ti ti-device-desktop',
                'has_page' => true,
                'url_path' => 'transaction',
                'route_name' => null,
                'slug' => 'point-of-sales',
                'level_sidebar' => 1,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Point of Sales > Method Payment
            [
                'id' => 'a0b1c2d3-0003-4a5b-8c9d-0e1f2a3b4c5e',
                'parent_id' => 'a0b1c2d3-e4f5-4a5b-8c9d-0e1f2a3b4c5e',
                'name' => 'Method Payment',
                'code' => 'method_payment',
                'text_sidebar' => 'Method Payment',
                'icon' => 'ti ti-credit-card',
                'has_page' => false,
                'url_path' => 'transaction/method-payment',
                'route_name' => 'pos.method-payment.index',
                'slug' => 'method-payment',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Point of Sales > POS
            [
                'id' => 'a0b1c2d3-0001-4a5b-8c9d-0e1f2a3b4c5e',
                'parent_id' => 'a0b1c2d3-e4f5-4a5b-8c9d-0e1f2a3b4c5e',
                'name' => 'POS',
                'code' => 'pos',
                'text_sidebar' => 'POS',
                'icon' => 'ti ti-device-desktop',
                'has_page' => false,
                'url_path' => 'transaction/pos',
                'route_name' => 'transaction.pos',
                'slug' => 'pos',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Point of Sales > Transaction
            [
                'id' => 'a0b1c2d3-0002-4a5b-8c9d-0e1f2a3b4c5e',
                'parent_id' => 'a0b1c2d3-e4f5-4a5b-8c9d-0e1f2a3b4c5e',
                'name' => 'Transaction',
                'code' => 'transaction',
                'text_sidebar' => 'Transaction',
                'icon' => 'ti ti-receipt',
                'has_page' => false,
                'url_path' => 'transaction',
                'route_name' => 'transaction.index',
                'slug' => 'transaction',
                'level_sidebar' => 2,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Business (Parent)
            [
                'id' => 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d',
                'parent_id' => null,
                'name' => 'Business',
                'code' => 'business',
                'text_sidebar' => 'Business',
                'icon' => 'ti ti-building-arch',
                'has_page' => true,
                'url_path' => 'business',
                'route_name' => null,
                'slug' => 'business',
                'level_sidebar' => 1,
                'order_number' => 7,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Business > Holding
            [
                'id' => 'b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e',
                'parent_id' => 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d',
                'name' => 'Holding',
                'code' => 'holding',
                'text_sidebar' => 'Holding',
                'icon' => 'ti ti-building-community',
                'has_page' => false,
                'url_path' => 'business/holding',
                'route_name' => 'holding.index.view',
                'slug' => 'holding',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Business > Company
            [
                'id' => 'c3d4e5f6-a7b8-4c7d-0e1f-2a3b4c5d6e7f',
                'parent_id' => 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d',
                'name' => 'Company',
                'code' => 'company',
                'text_sidebar' => 'Company',
                'icon' => 'ti ti-building-factory-2',
                'has_page' => false,
                'url_path' => 'business/company',
                'route_name' => 'company.index.view',
                'slug' => 'company',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Business > Branch
            [
                'id' => 'd4e5f6a7-b8c9-4d7e-1f2a-2a3b4c5d6e7f',
                'parent_id' => 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d',
                'name' => 'Branch',
                'code' => 'branch',
                'text_sidebar' => 'Branch',
                'icon' => 'ti ti-building-store',
                'has_page' => false,
                'url_path' => 'business/branch',
                'route_name' => 'branch.index.view',
                'slug' => 'branch',
                'level_sidebar' => 2,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings (Parent)
            [
                'id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'parent_id' => null,
                'name' => 'Settings',
                'code' => 'settings',
                'text_sidebar' => 'Settings',
                'icon' => 'ti ti-settings',
                'has_page' => true,
                'url_path' => 'settings',
                'route_name' => null,
                'slug' => 'settings',
                'level_sidebar' => 1,
                'order_number' => 9,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // === Reporting (Parent) ===
            [
                'id' => 'e2345678-9abc-cdef-0123-456789abcdef',
                'parent_id' => null,
                'name' => 'Reporting',
                'code' => 'reporting',
                'text_sidebar' => 'Reporting',
                'icon' => 'ti ti-chart-bar',
                'has_page' => true,
                'url_path' => 'reporting',
                'route_name' => null,
                'slug' => 'reporting',
                'level_sidebar' => 1,
                'order_number' => 8,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Reporting > Executive & Overview
            [
                'id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-9abc-cdef-0123-456789abcdef',
                'name' => 'Executive & Overview',
                'code' => 'reporting_executive_overview',
                'text_sidebar' => 'Executive & Overview',
                'icon' => 'ti ti-presentation',
                'has_page' => true,
                'url_path' => 'reporting/executive-overview',
                'route_name' => null,
                'slug' => 'reporting-executive-overview',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0002-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'name' => 'Executive Dashboard',
                'code' => 'reporting_executive_dashboard',
                'text_sidebar' => 'Executive Dashboard',
                'icon' => 'ti ti-dashboard',
                'has_page' => false,
                'url_path' => 'reporting/executive-dashboard',
                'route_name' => 'reporting.executive-dashboard.index',
                'slug' => 'reporting-executive-dashboard',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0003-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'name' => 'KPI Dashboard',
                'code' => 'reporting_kpi_dashboard',
                'text_sidebar' => 'KPI Dashboard',
                'icon' => 'ti ti-chart-infographic',
                'has_page' => true,
                'url_path' => 'reporting/kpi-dashboard',
                'route_name' => 'reporting.kpi-dashboard.index',
                'slug' => 'reporting-kpi-dashboard',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0004-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'name' => 'Multi-Outlet Comparison',
                'code' => 'reporting_multi_outlet_comparison',
                'text_sidebar' => 'Multi-Outlet Comparison',
                'icon' => 'ti ti-git-compare',
                'has_page' => false,
                'url_path' => 'reporting/multi-outlet-comparison',
                'route_name' => 'reporting.multi-outlet-comparison.index',
                'slug' => 'reporting-multi-outlet-comparison',
                'level_sidebar' => 3,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0005-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'name' => 'Revenue Trend',
                'code' => 'reporting_revenue_trend',
                'text_sidebar' => 'Revenue Trend',
                'icon' => 'ti ti-chart-line',
                'has_page' => false,
                'url_path' => 'reporting/revenue-trend',
                'route_name' => 'reporting.revenue-trend.index',
                'slug' => 'reporting-revenue-trend',
                'level_sidebar' => 3,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0006-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'name' => 'Profitability Overview',
                'code' => 'reporting_profitability_overview',
                'text_sidebar' => 'Profitability Overview',
                'icon' => 'ti ti-report-money',
                'has_page' => true,
                'url_path' => 'reporting/profitability-overview',
                'route_name' => 'reporting.profitability-overview.index',
                'slug' => 'reporting-profitability-overview',
                'level_sidebar' => 3,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0007-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0001-cdef-0123-456789abcdef',
                'name' => 'Business Unit Performance',
                'code' => 'reporting_business_unit_performance',
                'text_sidebar' => 'Business Unit Performance',
                'icon' => 'ti ti-building-store',
                'has_page' => false,
                'url_path' => 'reporting/business-unit-performance',
                'route_name' => 'reporting.business-unit-performance.index',
                'slug' => 'reporting-business-unit-performance',
                'level_sidebar' => 3,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Reporting > Purchasing
            [
                'id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-9abc-cdef-0123-456789abcdef',
                'name' => 'Purchasing',
                'code' => 'reporting_purchasing',
                'text_sidebar' => 'Purchasing',
                'icon' => 'ti ti-shopping-cart',
                'has_page' => true,
                'url_path' => 'reporting/purchasing',
                'route_name' => null,
                'slug' => 'reporting-purchasing',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0012-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'name' => 'PO Summary',
                'code' => 'reporting_po_summary',
                'text_sidebar' => 'PO Summary',
                'icon' => 'ti ti-file-invoice',
                'has_page' => false,
                'url_path' => 'reporting/po-summary',
                'route_name' => 'reporting.po-summary.index',
                'slug' => 'reporting-po-summary',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0013-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'name' => 'PO Receiving / GRN',
                'code' => 'reporting_po_receiving_grn',
                'text_sidebar' => 'PO Receiving / GRN',
                'icon' => 'ti ti-package-import',
                'has_page' => false,
                'url_path' => 'reporting/po-receiving-grn',
                'route_name' => 'reporting.po-receiving-grn.index',
                'slug' => 'reporting-po-receiving-grn',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0014-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'name' => 'PO Aging / Open PO',
                'code' => 'reporting_po_aging_open_po',
                'text_sidebar' => 'PO Aging / Open PO',
                'icon' => 'ti ti-clock-hour-4',
                'has_page' => false,
                'url_path' => 'reporting/po-aging-open-po',
                'route_name' => 'reporting.po-aging-open-po.index',
                'slug' => 'reporting-po-aging-open-po',
                'level_sidebar' => 3,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0015-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'name' => 'Purchase by Supplier',
                'code' => 'reporting_purchase_by_supplier',
                'text_sidebar' => 'Purchase by Supplier',
                'icon' => 'ti ti-truck-delivery',
                'has_page' => true,
                'url_path' => 'reporting/purchase-by-supplier',
                'route_name' => 'reporting.purchase-by-supplier.index',
                'slug' => 'reporting-purchase-by-supplier',
                'level_sidebar' => 3,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0016-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'name' => 'Purchase Price History',
                'code' => 'reporting_purchase_price_history',
                'text_sidebar' => 'Purchase Price History',
                'icon' => 'ti ti-history',
                'has_page' => true,
                'url_path' => 'reporting/purchase-price-history',
                'route_name' => 'reporting.purchase-price-history.index',
                'slug' => 'reporting-purchase-price-history',
                'level_sidebar' => 3,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0017-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0011-cdef-0123-456789abcdef',
                'name' => 'Supplier Performance',
                'code' => 'reporting_supplier_performance',
                'text_sidebar' => 'Supplier Performance',
                'icon' => 'ti ti-medal',
                'has_page' => true,
                'url_path' => 'reporting/supplier-performance',
                'route_name' => 'reporting.supplier-performance.index',
                'slug' => 'reporting-supplier-performance',
                'level_sidebar' => 3,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Reporting > Inventory & Warehouse
            [
                'id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-9abc-cdef-0123-456789abcdef',
                'name' => 'Inventory & Warehouse',
                'code' => 'reporting_inventory_warehouse',
                'text_sidebar' => 'Inventory & Warehouse',
                'icon' => 'ti ti-package',
                'has_page' => true,
                'url_path' => 'reporting/inventory-warehouse',
                'route_name' => null,
                'slug' => 'reporting-inventory-warehouse',
                'level_sidebar' => 2,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0022-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Stock On Hand',
                'code' => 'reporting_stock_on_hand',
                'text_sidebar' => 'Stock On Hand',
                'icon' => 'ti ti-box',
                'has_page' => false,
                'url_path' => 'reporting/stock-on-hand',
                'route_name' => 'reporting.stock-on-hand.index',
                'slug' => 'reporting-stock-on-hand',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0023-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Stock Card / Movement',
                'code' => 'reporting_stock_card_movement',
                'text_sidebar' => 'Stock Card / Movement',
                'icon' => 'ti ti-arrows-transfer-up-down',
                'has_page' => false,
                'url_path' => 'reporting/stock-card-movement',
                'route_name' => 'reporting.stock-card-movement.index',
                'slug' => 'reporting-stock-card-movement',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0024-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Stock Valuation',
                'code' => 'reporting_stock_valuation',
                'text_sidebar' => 'Stock Valuation',
                'icon' => 'ti ti-scale',
                'has_page' => true,
                'url_path' => 'reporting/stock-valuation',
                'route_name' => 'reporting.stock-valuation.index',
                'slug' => 'reporting-stock-valuation',
                'level_sidebar' => 3,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0025-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Low Stock / Reorder Alert',
                'code' => 'reporting_low_stock_reorder_alert',
                'text_sidebar' => 'Low Stock / Reorder Alert',
                'icon' => 'ti ti-alert-triangle',
                'has_page' => false,
                'url_path' => 'reporting/low-stock-reorder-alert',
                'route_name' => 'reporting.low-stock-reorder-alert.index',
                'slug' => 'reporting-low-stock-reorder-alert',
                'level_sidebar' => 3,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0026-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Stock Opname Variance',
                'code' => 'reporting_stock_opname_variance',
                'text_sidebar' => 'Stock Opname Variance',
                'icon' => 'ti ti-clipboard-data',
                'has_page' => false,
                'url_path' => 'reporting/stock-opname-variance',
                'route_name' => 'reporting.stock-opname-variance.index',
                'slug' => 'reporting-stock-opname-variance',
                'level_sidebar' => 3,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0027-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Stock Adjustment',
                'code' => 'reporting_stock_adjustment',
                'text_sidebar' => 'Stock Adjustment',
                'icon' => 'ti ti-adjustments-alt',
                'has_page' => false,
                'url_path' => 'reporting/stock-adjustment-report',
                'route_name' => 'reporting.stock-adjustment-report.index',
                'slug' => 'reporting-stock-adjustment',
                'level_sidebar' => 3,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0028-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Slow / Dead Stock',
                'code' => 'reporting_slow_dead_stock',
                'text_sidebar' => 'Slow / Dead Stock',
                'icon' => 'ti ti-battery-off',
                'has_page' => false,
                'url_path' => 'reporting/slow-dead-stock',
                'route_name' => 'reporting.slow-dead-stock.index',
                'slug' => 'reporting-slow-dead-stock',
                'level_sidebar' => 3,
                'order_number' => 7,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0029-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Inventory Aging',
                'code' => 'reporting_inventory_aging',
                'text_sidebar' => 'Inventory Aging',
                'icon' => 'ti ti-hourglass-high',
                'has_page' => true,
                'url_path' => 'reporting/inventory-aging',
                'route_name' => 'reporting.inventory-aging.index',
                'slug' => 'reporting-inventory-aging',
                'level_sidebar' => 3,
                'order_number' => 8,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0030-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0021-cdef-0123-456789abcdef',
                'name' => 'Negative Stock Analysis',
                'code' => 'reporting_negative_stock_analysis',
                'text_sidebar' => 'Negative Stock Analysis',
                'icon' => 'ti ti-chart-arrows-vertical',
                'has_page' => true,
                'url_path' => 'reporting/negative-stock-analysis',
                'route_name' => 'reporting.negative-stock-analysis.index',
                'slug' => 'reporting-negative-stock-analysis',
                'level_sidebar' => 3,
                'order_number' => 9,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Reporting > Sales & Transaction
            [
                'id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-9abc-cdef-0123-456789abcdef',
                'name' => 'Sales & Transaction',
                'code' => 'reporting_sales_transaction',
                'text_sidebar' => 'Sales & Transaction',
                'icon' => 'ti ti-cash-banknote',
                'has_page' => true,
                'url_path' => 'reporting/sales-transaction',
                'route_name' => null,
                'slug' => 'reporting-sales-transaction',
                'level_sidebar' => 2,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0032-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Sales Summary',
                'code' => 'reporting_sales_summary',
                'text_sidebar' => 'Sales Summary',
                'icon' => 'ti ti-chart-dots',
                'has_page' => false,
                'url_path' => 'reporting/sales-summary',
                'route_name' => 'reporting.sales-summary.index',
                'slug' => 'reporting-sales-summary',
                'level_sidebar' => 3,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0033-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Transaction Detail',
                'code' => 'reporting_transaction_detail',
                'text_sidebar' => 'Transaction Detail',
                'icon' => 'ti ti-receipt',
                'has_page' => false,
                'url_path' => 'reporting/transaction-detail',
                'route_name' => 'reporting.transaction-detail.index',
                'slug' => 'reporting-transaction-detail',
                'level_sidebar' => 3,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0034-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Sales by Payment Method',
                'code' => 'reporting_sales_by_payment_method',
                'text_sidebar' => 'Sales by Payment Method',
                'icon' => 'ti ti-credit-card',
                'has_page' => false,
                'url_path' => 'reporting/sales-by-payment-method',
                'route_name' => 'reporting.sales-by-payment-method.index',
                'slug' => 'reporting-sales-by-payment-method',
                'level_sidebar' => 3,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0035-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Sales by Cashier',
                'code' => 'reporting_sales_by_cashier',
                'text_sidebar' => 'Sales by Cashier',
                'icon' => 'ti ti-user',
                'has_page' => true,
                'url_path' => 'reporting/sales-by-cashier',
                'route_name' => 'reporting.sales-by-cashier.index',
                'slug' => 'reporting-sales-by-cashier',
                'level_sidebar' => 3,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0036-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Sales by Outlet',
                'code' => 'reporting_sales_by_outlet',
                'text_sidebar' => 'Sales by Outlet',
                'icon' => 'ti ti-building-store',
                'has_page' => false,
                'url_path' => 'reporting/sales-by-outlet',
                'route_name' => 'reporting.sales-by-outlet.index',
                'slug' => 'reporting-sales-by-outlet',
                'level_sidebar' => 3,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0037-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Sales by Customer',
                'code' => 'reporting_sales_by_customer',
                'text_sidebar' => 'Sales by Customer',
                'icon' => 'ti ti-users',
                'has_page' => false,
                'url_path' => 'reporting/sales-by-customer',
                'route_name' => 'reporting.sales-by-customer.index',
                'slug' => 'reporting-sales-by-customer',
                'level_sidebar' => 3,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0038-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Sales Return & Refund',
                'code' => 'reporting_sales_return_refund',
                'text_sidebar' => 'Sales Return & Refund',
                'icon' => 'ti ti-arrow-back-up',
                'has_page' => false,
                'url_path' => 'reporting/sales-return-refund',
                'route_name' => 'reporting.sales-return-refund.index',
                'slug' => 'reporting-sales-return-refund',
                'level_sidebar' => 3,
                'order_number' => 7,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0039-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Top Products & Categories',
                'code' => 'reporting_top_products_categories',
                'text_sidebar' => 'Top Products & Categories',
                'icon' => 'ti ti-trophy',
                'has_page' => false,
                'url_path' => 'reporting/top-products-categories',
                'route_name' => 'reporting.top-products-categories.index',
                'slug' => 'reporting-top-products-categories',
                'level_sidebar' => 3,
                'order_number' => 8,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            [
                'id' => 'e2345678-0040-cdef-0123-456789abcdef',
                'parent_id' => 'e2345678-0031-cdef-0123-456789abcdef',
                'name' => 'Hourly / Daily Trend',
                'code' => 'reporting_hourly_daily_trend',
                'text_sidebar' => 'Hourly / Daily Trend',
                'icon' => 'ti ti-chart-histogram',
                'has_page' => false,
                'url_path' => 'reporting/hourly-daily-trend',
                'route_name' => 'reporting.hourly-daily-trend.index',
                'slug' => 'reporting-hourly-daily-trend',
                'level_sidebar' => 3,
                'order_number' => 9,
                'is_label' => false,
                'has_create' => false,
                'has_update' => false,
                'has_read' => true,
                'has_delete' => false,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings > Menu
            [
                'id' => 'd2345678-9abc-def0-1234-56789abcdef0',
                'parent_id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'name' => 'Menu',
                'code' => 'menu',
                'text_sidebar' => 'Menu Management',
                'icon' => 'ti ti-menu-2',
                'has_page' => false,
                'url_path' => 'access-management/menu',
                'route_name' => 'menu.index.view',
                'slug' => 'menu',
                'level_sidebar' => 2,
                'order_number' => 1,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings > Role
            [
                'id' => '9d3ec3b4-6da1-490d-ae35-2e27d3fcc8a4',
                'parent_id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'name' => 'Role',
                'code' => 'roles',
                'text_sidebar' => 'Roles Management',
                'icon' => 'ti ti-shield-check',
                'has_page' => false,
                'url_path' => 'access-management/roles',
                'route_name' => 'roles.index.view',
                'slug' => 'roles',
                'level_sidebar' => 2,
                'order_number' => 2,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings > Configuration
            [
                'id' => 'e4567890-bcde-f012-3456-789abcdef012',
                'parent_id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'name' => 'Configuration',
                'code' => 'dashboard_configuration',
                'text_sidebar' => 'Dashboard Configuration',
                'icon' => 'ti ti-dashboard',
                'has_page' => false,
                'url_path' => 'access-management/dashboard-configuration',
                'route_name' => 'dashboard-configuration.index',
                'slug' => 'dashboard-configuration',
                'level_sidebar' => 2,
                'order_number' => 3,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings > Notification Config
            [
                'id' => 'f5678901-cdef-0123-4567-89abcdef0123',
                'parent_id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'name' => 'Notification Config',
                'code' => 'notifications',
                'text_sidebar' => 'Notification Config',
                'icon' => 'ti ti-bell',
                'has_page' => false,
                'url_path' => 'access-management/notifications/config',
                'route_name' => 'notifications.index.view',
                'slug' => 'notifications',
                'level_sidebar' => 2,
                'order_number' => 4,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings > Parameter
            [
                'id' => 'a6789012-def0-4234-5678-9abcdef01234',
                'parent_id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'name' => 'Parameter',
                'code' => 'parameter',
                'text_sidebar' => 'Parameter',
                'icon' => 'ti ti-list-details',
                'has_page' => false,
                'url_path' => 'master-data/parameter',
                'route_name' => 'parameter.index.view',
                'slug' => 'parameter',
                'level_sidebar' => 2,
                'order_number' => 5,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
            // Settings > Membership Configuration (CRM)
            [
                'id' => 'b7890123-def0-4234-5678-9abcdef01234',
                'parent_id' => 'c1234567-89ab-cdef-0123-456789abcdef',
                'name' => 'Membership Configuration',
                'code' => 'membership_configuration',
                'text_sidebar' => 'Membership Configuration',
                'icon' => 'ti ti-stars',
                'has_page' => false,
                'url_path' => 'crm/membership-configuration',
                'route_name' => 'crm.membership-configuration.index.view',
                'slug' => 'membership-configuration',
                'level_sidebar' => 2,
                'order_number' => 6,
                'is_label' => false,
                'has_create' => true,
                'has_update' => true,
                'has_read' => true,
                'has_delete' => true,
                'has_custom1' => false,
                'has_custom2' => false,
                'has_custom3' => false,
                'has_custom4' => false,
                'has_custom5' => false,
            ],
        ];

        // Truncate table first (PostgreSQL friendly)
        DB::statement('TRUNCATE TABLE master_data.menus RESTART IDENTITY CASCADE');

        // Insert new menus
        foreach ($menus as $menu) {
            Menu::create($menu);
        }

        $this->command->info('Menus seeded successfully!');
    }
}
